import { CelebrationMessage, StickerColor } from '../types';

// 스티커 아이템 데이터
export const STICKER_COLORS: StickerColor[] = [
	'#FADADD',
	'#FFE4E1',
	'#FFB6C1',
	'#FFBCD9',
	'#FFCBDB',
	'#FFDDE2',
	'#EDCDC2',
	'#FFDAB9',
	'#FFE5B4',
	'#FBCEB1',
	'#FFD8B1',
	'#F8B878',
	'#F7E7CE',
	'#F08080',
	'#FDBCB4',
	'#FFA07A',
	'#FAF884',
	'#FFFFE0',
	'#FFFACD',
	'#FFFDD0',
	'#FAFAD2',
	'#F9E2AE',
	'#F5F5DC',
	'#F3E5AB',
	'#FFF9DB',
	'#FFFFF0',
	'#F0FFF0',
	'#F5FFFA',
	'#AAF0D1',
	'#D0F0C0',
	'#ACE1AF',
	'#AAFAC8',
	'#A7F2C3',
	'#B2D8D8',
	'#B0E0E6',
	'#AEC6CF',
	'#BFEFFF',
	'#E0FFFF',
	'#87CEEB',
	'#F0F8FF',
	'#87CEFA',
	'#BCD4E6',
	'#BCD4E6',
	'#CCCCFF',
	'#E3E4FA',
	'#E6E6FA',
	'#D8BFD8',
	'#CBC3E3',
	'#E0BBE4',
	'#F2BDCD',
	'#C9A0DC',
	'#CB99C9',
	'#D8B7DD',
	'#DCAE96',
	'#FFE0E5',
	'#FFF5EE',
	'#FAF0E6',
	'#BC8F8F',
	'#FAEBD7',
	'#EFDECD',
	'#FFE4C4',
	'#F5DEB3',
	'#EEDC82',
	'#CBAE82',
	'#BC987E',
	'#CFCFC4',
	'#DCDCDC',
	'#D3D3D3',
	'#F8F8FF',
	'#FFFAF0',
	'#FFFAFA',
	'#E9D6EC',
	'#C9D2D2',
	'#D6F1FF',
	'#F6D1C1',
	'#B2FFFF',
	'#F0FFFF',
	'#AFEEEE',
	'#DDEEFF',
	'#ADD8E6',
	'#F5F9FF',
	'#FFEBCD',
	'#F8C8DC',
	'#FFF0F5',
	'#F2C1D1',
	'#FFDDF4',
	'#FDE2E4',
	'#FFE5D9',
	'#EAD1DC',
	'#D6EAF8',
	'#E6DAF3',
	'#E8E8E8',
];

// 도전 아이콘 데이터
export const CHALLENGE_ICONS: string[] = [
	'🏃‍♂️',
	'📚',
	'💧',
	'🧘‍♀️',
	'🌙',
	'🥗',
	'💪',
	'🎯',
	'🎵',
	'✍️',
	'🌱',
	'✨',
	'🛌',
	'🔥',
	'💡',
	'🧹',
	'🌞',
	'⭐',
];

// 도전 기간 옵션
export const CHALLENGE_DURATIONS: number[] = [7, 14, 21, 30];

// 마일스톤 데이터
export const MILESTONES: number[] = [1, 3, 5, 7, 10, 15, 20, 25, 30];

export const DEFAULT_CELEBRATIONS: CelebrationMessage[] = [
	{
		title: '또 하나 완료!',
		// subtitle: '+5 XP',
		description: '작은 실천이 큰 변화를 만들어요\n오늘도 잘하고 있어요! 👍',
		icon: '✅',
	},
	{
		title: '좋아요!',
		// subtitle: '+5 XP',
		description: '매일의 작은 성취가\n나를 더 나은 사람으로 만들어요 🌟',
		icon: '😊',
	},
	{
		title: '한 걸음 더!',
		description: '조금씩 나아가는 지금 이 순간이\n가장 중요해요 🚶‍♂️',
		icon: '👣',
	},
	{
		title: '계속해볼까요?',
		description: '지금처럼만 해도 충분해요\n천천히, 하지만 확실하게 🐢',
		icon: '🍀',
	},
	{
		title: '잘하고 있어요!',
		description: '작은 습관이 쌓여\n놀라운 변화를 만들어낼 거예요 🌈',
		icon: '💡',
	},
	{
		title: '멋져요!',
		description: '자신을 위한 실천\n그게 바로 최고의 투자예요 💖',
		icon: '🌟',
	},
];

// 축하 메시지 데이터
export const CELEBRATION_MESSAGES: CelebrationMessage[] = [
	{
		title: '첫 번째 스티커!',
		// subtitle: '+10 XP',
		description: '새로운 여정의 시작이에요!\n첫 걸음을 내딛었네요 🎯',
		icon: '🌟',
	},
	{
		title: '3개 달성!',
		// subtitle: '+15 XP',
		description: '습관의 씨앗이 싹트고 있어요\n이대로 계속 해보세요! 💪',
		icon: '🌱',
	},
	{
		title: '5개 달성!',
		// subtitle: '+20 XP',
		description: '꾸준함이 빛을 발하고 있어요\n정말 멋진 성과예요! ✨',
		icon: '⭐',
	},
	{
		title: '7개 달성!',
		// subtitle: '+25 XP',
		description: '7개의 스티커를 모았어요\n이제 진짜 습관이 되어가네요 🔥',
		icon: '🏆',
	},
	{
		title: '10개 달성!',
		description: '10개의 성취!\n쌓아온 결과가 자랑스러워요 🎉',
		icon: '🎖️',
	},
	{
		title: '15개 달성!',
		description: '절반을 훌쩍 넘었어요\n포기하지 않은 당신이 멋져요 💯',
		icon: '🥇',
	},
	{
		title: '20개 달성!',
		description: '이젠 꽤 익숙해졌죠?\n당신만의 리듬을 잘 찾아가고 있어요 🧭',
		icon: '👑',
	},
	{
		title: '25개 달성!',
		description: '조금씩 쌓아온 노력이\n이제 눈에 보이기 시작해요 🌟',
		icon: '📈',
	},
	{
		title: '30개 달성!',
		description:
			'여기까지 온 당신, 정말 대단해요\n곧 마지막 선물이 기다리고 있어요 🎊',
		icon: '🎯',
	},
	{
		title: '최종 달성!',
		description: '목표 달성!\n자신을 향한 최고의 선물이에요 🎁',
		icon: '🚀',
	},
];
